### ISSUE TITLE
При повороте экрана на странице вопроса приложение падает (entry == null)

### ISSUE THREAD

**Issue by alekseyl1992** [tech-team/decider-android#14]

**Comment by igorcoding** [comment]
хоть бы стектрейс)

**Comment by alekseyl1992** [comment]
зачем?
entry == null
написано же
везде, на всех обращениях

думаю, стоит вместо поля класса таки юзать аргументы AsyncTask'а: aVoid
или не юзать асинктаски

**Comment by igorcoding** [comment]
забей, проблема не в этом, в том, что qid не сохранялся в бандл

**Comment by igorcoding** [comment]
я правлю
