### ISSUE TITLE
Что-то deprecated

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#18]
org.techteam.decider I/ViewUtils﹕ app:theme is now deprecated. Please move to using android:theme instead.

**Comment by alekseyl1992** [comment]
там запутанная ситуация
есть app:theme, его можно заменить на android:theme
есть app:popupTheme, если его заменить, то ругается на то, что не используется на < API 21 (5.0)
и есть app:title

в целом выглядит как-то криво:

app:title
android:theme
app:popupTheme

**Comment by alekseyl1992** [comment]
и ещё вопрос - а где этот ворнинг можно узреть?
Messages, Gradle Console, Runtime Console
нигде не нашёл, но своими глазами ранее видел

в целом, с учётом вышесказанного, предлагаю тупо закрыть issue, не корёжить код и не тратить время

**Comment by igorcoding** [comment]
Пускай повисит, руки дойдут - посмотрим
