### ISSUE TITLE
Создание вопроса. Добавить предупреждение о потере данных.

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#26]
Добавить сообщение, которые показывалось юзеру, если он пытается уйти с экрана создания вопроса (по кнопке назад вероятнее всего), что данные будут стерты.

Ибо пока я не нашел способа сохранить данные где-то при уничтожении фрагмента (saveInstanceState вызывается только при уничтожении активити)
Возможно можно будет сохранить либо в базу, либо в SharedPreferences

**Comment by alekseyl1992** [comment]
Бооольше любви к фрагментам
в смысле надо сделать активити..

**Comment by igorcoding** [comment]
Не спеши, пожалуйста
