### ISSUE TITLE
Очистка кэша WebView

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#37]
Понять, в какой момент надо чистить кэш WebView, чтобы юзер мог зайти под, скажем, другой учеткой вк, при этом, чтоб ему не надо было каждый раз вводить логин пароль в вк

**Comment by alekseyl1992** [comment]
а кэш WebView и кэш встроенного браузера (хрома) - разные вещи, да?

**Comment by igorcoding** [comment]
Да, у веб вью есть метод на очистку кеша, осталось лишь понять, когда вызывать его

**Comment by alekseyl1992** [comment]
Думаю, будет здраво это делать по нажатию Logout, так что это #3
