### ISSUE TITLE
Разобраться с тем, как мы будем "догонять" сервер в плане комментариев

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#49]

**Comment by alekseyl1992** [comment]
ну вот как это происходит на форуме, например
ты постишь.. и попадаешь на обновлённый список вопросов..
в ВК там постоянно всё обновляется.. нам такое не подходит

в целом я бы так сказал:
вариант, что юзер написал коммент, а мы его вообще не показали нам не подходит
вариант, что мы добавили только этот коммент - тоже
потому что раз мы обновляем список, то обновляем с сервера

остаётся вопрос - скроллить к его комменту или нет?
ну в идеале да
но я б не стал заморачиваться
чтоб это стало актуальным, надо чтобы одновременно запостили хотябы 5 комментов (жа-да, я помню, с момента открытия вопроса, до момента отправки)

так что так:
написал коммент, отправили на серв, обновили список, и проскроллили в самый низ, либо к комменту автора

**Comment by alekseyl1992** [comment]
а, ещё кажется была проблема с загрузкой по 30 комментов, да?
я б не парился и грузил все..
в противном случае, конечно же, надо грузить нижние 30 и добавлять вверху кнопку подгрузки

**Comment by igorcoding** [comment]
>  проскроллили в самый низ, либо к комменту автора

я считаю должно обязательно соблюдаться, что коммент автора - последний

**Comment by igorcoding** [comment]
Сюда же входит работа по дполнению списка после CreateComment
