### ISSUE TITLE
Интегрировать AccountManager

### ISSUE THREAD

**Issue by alekseyl1992** [tech-team/decider-android#6]

**Comment by alekseyl1992** [comment]
http://www.finalconcept.com.au/article/view/android-account-manager-step-by-step-2
http://blog.udinic.com/2013/04/24/write-your-own-android-authenticator/

**Comment by igorcoding** [comment]
Реализовать дополнительную логику по обработке expires у токена + добавить инвалидацию токена при неудачном запросе на серв, дабы произошел рефреш токена
